### ISSUE TITLE
Refactor API Guide: QE checklist

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-files#76]
# Refactor API Guide: QE checklist

Use the following checklist to verify that API guide refactoring for each service. If you have questions, open a [docs-common issue](https://github.com/rackerlabs/docs-common/issues/new).  

Do the QE check against the PR submitted to the master repo.  Ask the person who did the refactoring to make you a collaborator on their fork in case you want to submit a PR to correct something. 

When you build the refactored Sphinx project, use the ``make clean html`` command to build chunked content. 

- [x] Review the [Strider build log](https://build.developer.rackspace.com/) for errors. Notify author about any issues.
- [x] Check for broken links.
- [x] Verify that navigation matches the [API Guide template](https://staging.developer.rackspace.com/staging.horse/build-2ecafb8a99/docs/api-doc-template/).
- [x] Check the *API reference* section to verify that the methods for each resource are in a single topic.
- [x] Check the *General API information* topics to make sure they match the common content where possible.
- [x] Check the *Authentication* topic in the Getting started section to make sure it matches the [common template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/getting-started/authenticate.rst).
- [x] Check ``conf.py`` to make sure it has the updates from the 
       [template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/conf.py).
- [x] Verify that you can [build locally from source](https://github.com/rackerlabs/docs-rackspace/blob/master/doc/tools/build-from-source.rst).

**Comment by cyrichardson** [comment]
Will also need to find a volunteer to QE when this is ready.

**Comment by cyrichardson** [comment]
@catlook Differences in files for Cloud Files noted in https://github.com/rackerlabs/docs-common/issues/62.

**Comment by catlook** [comment]
strider build clean except the "./getting-started/authenticate.rst:1: WARNING: Could not lex literal_block as "json". Highlighting skipped." warning which sometimes shows up but appears to have no impact

**Comment by catlook** [comment]
in CDN container services operations there is a section: Any URIs set in the older format (for example, http://c25810.r10.cf1.rackcdn.com/mydog.jpg) continue to work. However, any newly generated CDN URIs have the new format, as shown in the following example: http://80745c48926cd286a5a0-48261ebe0e4c795a565ece6b9cca2fe8.r10.cf1.rackcdn.com/mydog.jpg.    Both URLs are hyperlinked and neither work.  If they are intended to just show the structure of a URL, I'd recommend removing the hyperlink.

**Comment by catlook** [comment]
You have your use cases under the API Ref, but I think they really belong in the Getting Started.

**Comment by catlook** [comment]
In form post use case there is another URL that i think should not be hyperlinked: Optionally, you can also include a prefix to separate uploads, such as assigning each user a certain prefix:

    https://storage.clouddrive.com/v1/yourAccountID/container/object_prefix.

**Comment by cyrichardson** [comment]
@catlook Per your slack comment, I am adding backticks to response codes throughout the document now.

**Comment by cyrichardson** [comment]
@catlook: Per your slack comment, I also changed the link to point to the HTTP response codes section in the Identity content.

**Comment by catlook** [comment]
conf.py
# General information about the project.
project = 'Rackspace Cloud Files v1.0'
copyright = '2016, Rackspace'    <---should just be '2016', not '2016, Rackspace'
author = 'Rackspace'

**Comment by catlook** [comment]
conf.py

texinfo_documents = [
  (master_doc, 'docs-cloud-files', 'Rackspace Cloud Files API Documentation',
   'Rackspace', 'docs-cloud-files', 'Learn about using the Product',  <--- should be 'Learn about using Cloud Files'
   'Miscellaneous'),
]

**Comment by catlook** [comment]
Done...proceed apace!
